### ISSUE TITLE
SyntaxError: 'return' outside of function

### ISSUE THREAD

**Issue by loretoparisi** [yue/yackage#1]
I'm packaging a express application. I get

```
$ yackage --platform win32 --arch ia32 --app-dir /Users/loretoparisi/Documents/Projects/webapp/  build out

events.js:183
      throw er; // Unhandled 'error' event
      ^
SyntaxError: 'return' outside of function
    at JS_Parse_Error.get (eval at <anonymous> (/usr/local/lib/node_modules/yackage/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
```

**Comment by zcbenz** [comment]
Fixed with https://github.com/yue/yackage/commit/3947bce1bd4f8288ec4b6b864d7c34ac9c7dca5d in v0.1.2.

**Comment by loretoparisi** [comment]
@zcbenz thanks! I have installed `$ yackage -V v0.1.3`, and I have tried to run again

```
$ yackage build out

events.js:183
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unterminated string constant
    at JS_Parse_Error.get (eval at <anonymous> (/usr/local/lib/node_modules/yackage/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
```

Normally I saw this error when using standard `uglify` (not the ES one) due to ECMA6 compatibility, but I can see that you are using `uglify-es`, so this should not be the problem. 
I'm using `$ uglifyjs -V uglify-es 3.3.9` and it works fine with my javascript files, so it should work with yackage as well I think.

**Comment by zcbenz** [comment]
It is probably from some dependencies used in your code, I'll add some debug information.

**Comment by loretoparisi** [comment]
@zcbenz how can add more debugging info?

**Comment by zcbenz** [comment]
Yackage works by packing the app with `npm pack` first, it seems that the submodules are not included by your app's package.

See also https://github.com/yue/yackage#how-yackage-works.

**Comment by loretoparisi** [comment]
@zcbenz ok it makes sense! How to package my submodules then within the app?

**Comment by loretoparisi** [comment]
@zcbenz hello, I was able to fix the submodules path issues, using local submodules (`file` directive in the `package.json` file). Thanks for your help.
