### ISSUE TITLE
Reached rate limit on the API because of release checking 

### ISSUE THREAD

**Issue by soyuka** [yue/yackage#3]

**Comment by zcbenz** [comment]
Can you clarify more on this? I don't know any code in Yackage would cause API rate limits.

**Comment by soyuka** [comment]
Whoops really sorry about that thought I wrote it!

https://github.com/yue/yackage/blob/d841d934b3dc6a163f97ea7002ad7ec84a899e30/lib/main.js#L121 

this line calls the github api everytime I launch `yackage start` and I kinda did it a lot while debugging :).

The first solution that came in mind is to keep the latest value in cache for a day. I can implement this if you want, lmk.

**Comment by zcbenz** [comment]
A pull request would be awesome. A 10 minutes cache should be enough though.
