### ISSUE TITLE
Binary is larger than expected

### ISSUE THREAD

**Issue by computerquip-streamlabs** [yue/yackage#8]
My full node_modules and application code is ~2MB. The yode runtime itself ~22MB. However, yode dist results in a binary that's ~45MB in size, suspiciously almost double what I would expect. Using 7z and LZMA2 compression, it compresses down to ~6MB as well which is suspicious.

Unfortunately, DEFLATE doesn't do so hot here giving me a compressed size of ~16MB, which is a bit of an immediate problem for me given I'm serving the package compressed with Zlib and DEFLATE. I might consider an LZMA approach in the future (since I just figured out there are native Javascript implementations of LZMA, holy cow) but still somewhat inconvenient.

**Comment by zcbenz** [comment]
Did you add `out` and `yode` to `.gitignore`? You can see if your distribution includes unnecessary files by checking the archive generated by `npm pack`.

**Comment by computerquip-streamlabs** [comment]
That was it, thanks. Closing...
